const mongoose = require("mongoose");

const VideoSchema = mongoose.Schema(
  {
    url: {
      type: String,
      require: [true, "url is required"],
    },
    title: {
      type: String,
    },
    thumbnail: {
      type: String,
    },

    translatedTranscript: [
      {
        type: String,
      },
    ],
    availableCaptions: [
      {
        id: String,
        language: String,
        name: String,
        isAutoGenerated: Boolean,
      },
    ],
    defaultCaptionData: {
      name: { type: String },
      transcript: [
        {
          dur: { type: String, required: true },
          start: { type: String, required: true },
          text: { type: String, required: true },
        },
      ],
      translatedTranscript: [{ type: String, required: true }],
    },

    userId: {
      type: mongoose.Types.ObjectId,
      ref: "User",
    },
    playlistId: {
      type: mongoose.Types.ObjectId,
      ref: "Playlist",
    },
  },
  {
    toJSON: { virtuals: true }, // Ensure virtuals are included in JSON output
    timestamps: true,
    toObject: { virtuals: true }, // Ensure virtuals are included in object output
  }
);

VideoSchema.pre("find", function (next) {
  this.sort({ createdAt: -1 }); // Sort by createdAt in descending order (newest first)
  next();
});

VideoSchema.virtual("videoCards", {
  ref: "Card",
  localField: "_id",
  foreignField: "videoId",
});

const VideoModel = mongoose.model("Video", VideoSchema);

module.exports = VideoModel;
